server:
  port: 8082

security:
  user:
    name: user
    password: test
    
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver   
    url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true     